# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=100, verbose_name='Nome da Pergunta')),
                ('opcao1', models.CharField(max_length=100, verbose_name='Op\xe7\xe3o 1')),
                ('opcao2', models.CharField(max_length=100, verbose_name='Op\xe7\xe3o 2')),
                ('opcao3', models.CharField(max_length=100, verbose_name='Op\xe7\xe3o 3')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
