# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='opcao1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Op\xe7\xe3o 1'),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='opcao2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Op\xe7\xe3o 2'),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='opcao3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Op\xe7\xe3o 3'),
        ),
    ]
